"""empty message

Revision ID: 94ded4d95672
Revises: fc7ccb4bfc72
Create Date: 2025-03-17 14:22:42.601819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ded4d95672'
down_revision = 'fc7ccb4bfc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column("frequency", type_=sa.Integer(), postgresql_using="frequency::integer")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmaceutical', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column("frequency", type_=sa.String())

    # ### end Alembic commands ###
