"""empty message

Revision ID: db03f2ce4c62
Revises: 94ded4d95672
Create Date: 2025-03-17 14:50:31.192264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db03f2ce4c62'
down_revision = '94ded4d95672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('pharmaceutical')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmaceutical', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
